name: Docker Tests
on: [push, pull_request]

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
    publish_docker:
        name: Upload container
        if: |
            github.repository == 'OpenDataCubePipelines/ard-pipeline'
            && github.event_name == 'push'

        runs-on: ubuntu-latest

        steps:
        -   name: Push Docker image
            run: |
                echo "this is a push event"
